/**
 * PostTestAnalytics Component — Real Post-Test Performance Analytics
 * ===================================================================
 * Visualizes ML evaluation sessions, mastery level distributions, and concept pass rates.
 */

import { SchemaMasteryAPI } from "../../api/api.js";

export async function renderPostTestAnalytics(container, onNavigate) {
    container.innerHTML = `
        <div style="display: flex; flex-direction: column; gap: 2rem;">
            
            <!-- Page Header -->
            <div style="display: flex; justify-content: space-between; align-items: flex-start; flex-wrap: wrap; gap: 1rem;">
                <div>
                    <h1 style="font-size: 1.75rem; font-weight: 800; color: #111827; letter-spacing: -0.02em;">
                        Post-Test ML Analytics
                    </h1>
                    <p style="color: #6B7280; font-size: 0.9375rem; margin-top: 0.25rem;">
                        Real-time student mastery validation outcomes generated by the trained Random Forest pipeline.
                    </p>
                </div>
            </div>

            <!-- Analytics Container -->
            <div id="analytics-content-area">
                <div style="text-align: center; padding: 3rem 0;"><div class="spinner"></div></div>
            </div>

        </div>
    `;

    await loadAnalytics();

    async function loadAnalytics() {
        const area = document.getElementById("analytics-content-area");
        if (!area) return;

        try {
            const data = await SchemaMasteryAPI.getTeacherOverview();
            const stats = data.stats || {};
            const totalSessions = stats.sessions_count || 0;

            if (totalSessions === 0) {
                area.innerHTML = `
                    <div class="card" style="text-align: center; padding: 4rem 1.5rem;">
                        <div style="width: 64px; height: 64px; border-radius: 50%; background: #EFF6FF; color: #1E40AF; display: inline-flex; align-items: center; justify-content: center; font-size: 1.75rem; margin-bottom: 1.25rem;">
                            <i class="fa-solid fa-chart-column"></i>
                        </div>
                        <h2 style="font-size: 1.35rem; font-weight: 800; color: #111827; margin-bottom: 0.5rem;">
                            No Post-Test Sessions Recorded Yet
                        </h2>
                        <p style="color: #6B7280; font-size: 0.9375rem; max-width: 500px; margin: 0 auto 1.5rem auto;">
                            As students complete the 15-question post-test assessments, their ML mastery evaluations and 4-tier answer breakdowns will appear here in real time.
                        </p>
                        <button class="btn btn-primary btn-sm" id="test-student-session-btn">
                            <i class="fa-solid fa-flask"></i> Run a Test Assessment as Student
                        </button>
                    </div>
                `;
                document.getElementById("test-student-session-btn")?.addEventListener("click", () => {
                    if (onNavigate) onNavigate("/student/dashboard");
                });
                return;
            }

            // If sessions exist, display analytics summary
            area.innerHTML = `
                <div style="display: flex; flex-direction: column; gap: 1.5rem;">
                    <div class="stat-card-grid">
                        <div class="stat-card">
                            <div class="stat-card-label">Total Post-Tests</div>
                            <div class="stat-card-val" style="color: #1E40AF;">${totalSessions}</div>
                            <div class="stat-card-desc">Completed sessions</div>
                        </div>

                        <div class="stat-card">
                            <div class="stat-card-label">Questions Evaluated</div>
                            <div class="stat-card-val" style="color: #059669;">${stats.attempts_count || (totalSessions * 15)}</div>
                            <div class="stat-card-desc">4-tier answer responses</div>
                        </div>

                        <div class="stat-card">
                            <div class="stat-card-label">ML Prediction Engine</div>
                            <div class="stat-card-val" style="color: #0284C7; font-size: 1.35rem;">Random Forest</div>
                            <div class="stat-card-desc"><code>schema_mastery_pipeline</code></div>
                        </div>

                        <div class="stat-card">
                            <div class="stat-card-label">Active Approved Pool</div>
                            <div class="stat-card-val" style="color: #D97706;">${stats.approved_active_count || 0}</div>
                            <div class="stat-card-desc">Questions in circulation</div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                <i class="fa-solid fa-microchip" style="color: #1E40AF;"></i> ML Model Performance Summary
                            </div>
                        </div>
                        <div style="display: flex; flex-direction: column; gap: 1rem; font-size: 0.875rem;">
                            <p style="color: #4B5563;">
                                The Schema Mastery model validates whether learners have transitioned from fragmented or fragile understanding to a robust, consolidated programming schema.
                            </p>
                            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem;">
                                <div style="background: #F9FAFB; border: 1px solid #E5E7EB; padding: 1rem; border-radius: 8px;">
                                    <div style="font-weight: 700; color: #111827; margin-bottom: 0.25rem;">Cognitive Model</div>
                                    <div style="color: #6B7280;">11-feature multi-source behavioral vector</div>
                                </div>
                                <div style="background: #F9FAFB; border: 1px solid #E5E7EB; padding: 1rem; border-radius: 8px;">
                                    <div style="font-weight: 700; color: #111827; margin-bottom: 0.25rem;">Outcome Classes</div>
                                    <div style="color: #6B7280;">DONE (Advance) vs LEARN_AGAIN (Remediation)</div>
                                </div>
                                <div style="background: #F9FAFB; border: 1px solid #E5E7EB; padding: 1rem; border-radius: 8px;">
                                    <div style="font-weight: 700; color: #111827; margin-bottom: 0.25rem;">Delivery Safety</div>
                                    <div style="color: #059669; font-weight: 600;"><i class="fa-solid fa-check"></i> Server-side option randomization</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            `;
        } catch (err) {
            area.innerHTML = `
                <div class="alert alert-danger">
                    <i class="fa-solid fa-triangle-exclamation"></i> Error loading analytics: ${err.message}
                </div>
            `;
        }
    }
}
